name       : libsass
version    : 3.4.8
release    : 5
source     :
    - https://github.com/sass/libsass/archive/3.4.8.tar.gz : 2344372fa613db1ef1401bea03abc23e824cb33b03ba2276ec56602dc8ab003f
license    : MIT
component  : programming.library
summary    : LibSass is a C/C++ port of the Sass CSS precompiler.
description: |
    LibSass is a C/C++ port of the Sass CSS precompiler.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
