name       : libsass
version    : 3.6.5
release    : 14
source     :
    - https://github.com/sass/libsass/archive/3.6.5.tar.gz : 89d8f2c46ae2b1b826b58ce7dde966a176bac41975b82e84ad46b01a55080582
homepage   : https://sass-lang.com/libsass
license    : MIT
component  : programming.library
summary    : LibSass is a C/C++ port of the Sass CSS precompiler.
description: |
    LibSass is a C/C++ port of the Sass CSS precompiler.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
