name       : libsass
version    : 3.3.6
release    : 1
source     :
    - https://github.com/sass/libsass/archive/3.3.6.tar.gz : 4b004b0fcef55420dc916216b1961e0d86925e6bf4a6be37d0b6db42f7f25da5
license    : MIT
component  : programming
summary    : LibSass is a C/C++ port of the Sass CSS precompiler.
description: |
    LibSass is a C/C++ port of the Sass CSS precompiler.
setup      : |
    autoreconf -vfi
    %configure  --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 0644 LICENSE $installdir/usr/share/licenses/libsass/LICENSE
