name       : libsass
version    : 3.4.4
release    : 3
source     :
    - https://github.com/sass/libsass/archive/3.4.4.tar.gz : 1dc4d49a9a53b891b7e98935709e625f1d68782d87aef4304a41e6d590abb480
license    : MIT
component  : programming.library
summary    : LibSass is a C/C++ port of the Sass CSS precompiler.
description: |
    LibSass is a C/C++ port of the Sass CSS precompiler.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
