name       : libsass
version    : 3.5.4
release    : 9
source     :
    - https://github.com/sass/libsass/archive/3.5.4.tar.gz : 5f61cbcddaf8e6ef7a725fcfa5d05297becd7843960f245197ebb655ff868770
license    : MIT
component  : programming.library
summary    : LibSass is a C/C++ port of the Sass CSS precompiler.
description: |
    LibSass is a C/C++ port of the Sass CSS precompiler.
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
